In [1]:
%load_ext autoreload
% autoreload 2

In [33]:
import numpy as np

import solution_joe
from order import *

In [17]:
prices = [
			[30, 10,   10],
			[30, 20,   10],
			[30,  5,   10]
		]
qtys = [3,3,3]
seller = [
    (5, 50), # <<-- its a stab in the eye, but it's the only one that works
    (5, 10), # <<-- almost, we max out at $35
    (5, 10), # <<-- hit max, but doesn't have all products so no good
]

ctx = Context(prices, qtys, seller)

In [18]:
linopt = solution_joe.LinOpt(ctx)

In [19]:
linopt.get_c()

array([ 30.,  10.,  10.,  30.,  20.,  10.,  30.,   5.,  10.])

In [20]:
A_ub, b_ub = linopt.get_ub_constraints()

In [21]:
A_ub

array([[-30.,  -0.,  -0., -30.,  -0.,  -0., -30.,  -0.,  -0.],
       [ -0., -10.,  -0.,  -0., -20.,  -0.,  -0.,  -5.,  -0.],
       [ -0.,  -0., -10.,  -0.,  -0., -10.,  -0.,  -0., -10.]])

In [16]:
b_ub

array([-5, -5, -5])

In [22]:
A_eq, b_eq = linopt.get_eq_constraints()

In [23]:
A_eq

array([[ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.]])

In [24]:
b_eq

array([3, 3, 3])

In [25]:
res = linopt.create_order()

In [26]:
res

     fun: 78.333333333333343
 message: 'Optimization terminated successfully.'
     nit: 10
   slack: array([  0.        ,  40.        ,  23.33333333])
  status: 0
 success: True
       x: array([ 0.        ,  3.        ,  0.        ,  0.16666667,  0.        ,
        2.83333333,  0.        ,  3.        ,  0.        ])

In [29]:
res.x.reshape(3,3)

array([[ 0.        ,  3.        ,  0.        ],
       [ 0.16666667,  0.        ,  2.83333333],
       [ 0.        ,  3.        ,  0.        ]])

In [28]:
list(res.x)

[0.0, 3.0, 0.0, 0.16666666666666666, 0.0, 2.8333333333333335, 0.0, 3.0, 0.0]

In [34]:
np.array(prices)

array([[30, 10, 10],
       [30, 20, 10],
       [30,  5, 10]])

In [73]:
prices = [
    [1001, 101, 10, 10],
    [1002, 100, 50, 50],
    [1001, 101, 10, 10],
    [1002, 100, 50, 50],
    [1001, 101, 10, 10],
    [1002, 100, 50, 50],
    [1001, 101, 10, 10],
    [1002, 100, 50, 50],
    [1001, 101, 10, 10],
    [1002, 100, 50, 50],
]
qtys = [1, 2, 3, 1, 1, 2, 2, 3, 2, 1]
seller = [
    (0,1),
    (0,2),
    (0,3),
    (0,1)
]
ctx = Context(prices, qtys, seller)

linopt = solution_joe.LinOpt(ctx)
res = linopt.create_order()

In [74]:
res.x.reshape(10, 4)

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  3.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  3.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [75]:
A_ub, b_ub = linopt.get_ub_constraints()

In [76]:
A_ub

array([[-1001.,    -0.,    -0.,    -0., -1002.,    -0.,    -0.,    -0.,
        -1001.,    -0.,    -0.,    -0., -1002.,    -0.,    -0.,    -0.,
        -1001.,    -0.,    -0.,    -0., -1002.,    -0.,    -0.,    -0.,
        -1001.,    -0.,    -0.,    -0., -1002.,    -0.,    -0.,    -0.,
        -1001.,    -0.,    -0.,    -0., -1002.,    -0.,    -0.,    -0.],
       [   -0.,  -101.,    -0.,    -0.,    -0.,  -100.,    -0.,    -0.,
           -0.,  -101.,    -0.,    -0.,    -0.,  -100.,    -0.,    -0.,
           -0.,  -101.,    -0.,    -0.,    -0.,  -100.,    -0.,    -0.,
           -0.,  -101.,    -0.,    -0.,    -0.,  -100.,    -0.,    -0.,
           -0.,  -101.,    -0.,    -0.,    -0.,  -100.,    -0.,    -0.],
       [   -0.,    -0.,   -10.,    -0.,    -0.,    -0.,   -50.,    -0.,
           -0.,    -0.,   -10.,    -0.,    -0.,    -0.,   -50.,    -0.,
           -0.,    -0.,   -10.,    -0.,    -0.,    -0.,   -50.,    -0.,
           -0.,    -0.,   -10.,    -0.,    -0.,    -0.,   -50.

In [77]:
b_ub

array([0, 0, 0, 0])

In [42]:
from order import BruceForce

In [54]:
order = BruceForce(ctx).create_order()

In [55]:
order.total

541

In [56]:
res

     fun: 540.0
 message: 'Optimization terminated successfully.'
     nit: 20
   slack: array([   0.,    0.,  540.,    0.])
  status: 0
 success: True
       x: array([ 0.,  0.,  1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,
        2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  1.,  0.])

In [57]:
order.sellers

defaultdict(None, {103: 1})

In [58]:
from collections import defaultdict

In [59]:
dd = defaultdict(int)

In [60]:
dd[1] = 'yes'

In [84]:
%%timeit
prices = [
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],
    [1001, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10, 101, 10, 10],
    [1002, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50, 100, 50, 50],    
]
qtys = [1, 2, 3, 1, 1, 2, 2, 3, 2, 1,1, 2, 3, 1, 1, 2, 2, 3, 2, 1,1, 2, 3, 1, 1, 2, 2, 3, 2, 1,1, 2, 3, 1, 1, 2, 2, 3, 2, 1,1, 2, 3, 1, 1, 2, 2, 3, 2, 1]
seller = [
  (10,1),
  (0,2),
  (20,3),
  (0,1),
  (0,1),
  (30,2),
  (0,3),
  (0,1),
  (0,1),
  (10,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (20,3),
  (0,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (30,1),
  (0,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (40,3),
  (0,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (30,1),
  (0,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (10,3),
  (0,1),
  (0,1),
  (0,2),
  (0,3),
  (20,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (5,1),
  (0,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (10,3),
  (0,1),
  (10,1),
  (0,2),
  (10,3),
  (0,1),
  (0,1),
  (10,2),
  (0,3),
  (0,1),
  (10,1),
  (0,2),
  (0,3),
  (10,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (0,1),
  (10,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (10,1),
  (20,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (80,1),
  (0,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2),
  (0,3),
  (0,1),
  (0,1),
  (0,2)
]

ctx = Context(prices, qtys, seller)

linopt = solution_joe.LinOpt(ctx)
res = linopt.create_order()

1 loop, best of 3: 606 ms per loop


In [82]:
res

     fun: 2700.0
 message: 'Optimization terminated successfully.'
     nit: 100
   slack: array([    0.,     0.,  2700.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,   